export const COLORS: StyledColors = {
  anakiwa: "#A8FFF6",
  anzac: "#d9bf50",
  black: "#000000",
  blackPearl: "#07132b",
  blushPink: "#FF8EFF",
  blueRibbon: "#005cff",
  curiousBlue: "#2383DA",
  cyprus: "#004442",
  doveGray: "#707070",
  flushOrange: "#FF8003",
  fuchasiaPink: "#B655B6",
  indiaKhaki: "#C3B693",
  endeavour: "#005099",
  gradient1: "linear-gradient(#00b492 0%, #009fc7 100%)",
  mercury: "#E8E8E8",
  salem: "#078041",
  snowyMint: "#d0ffdc",
  summerGreen: "#92C498",
  verdunGreen: "#4F7D00",
  toryBlue: "#104C94",
  red: "#FF0000",
  rustyNail: "#7F5108",
  white: "#ffffff",
}

interface StyledColors {
  anakiwa: string,
  anzac: string,
  black: string,
  blackPearl: string,
  blushPink: string,
  blueRibbon: string,
  curiousBlue: string,
  cyprus: string,
  doveGray: string,
  flushOrange: string,
  fuchasiaPink: string,
  indiaKhaki: string,
  endeavour: string,
  gradient1: string,
  mercury: string,
  salem: string,
  snowyMint: string,
  summerGreen: string,
  verdunGreen: string,
  toryBlue: string,
  red: string,
  rustyNail: string,
  white: string,
}
